spring.application.name=TTracker
server.address=0.0.0.0
# spring.kafka.bootstrap-servers=172.31.0.1:9092
spring.kafka.bootstrap-servers=localhost:9092
gtfs.downloadpath= data/gtfs/gtfs.zip
gtfs.extractedFiles= data/gtfs/extracted
gtfs.selectedFiles= data/gtfs/selected


gtfs.url=https://media.ilevia.fr/opendata/gtfs.zip